### ISSUE TITLE
Locks up Beaker with larger files

### ISSUE THREAD

**Issue by kevinmarks** [kickscondor/duxtape#2]
I tried a very big one (179M), which plays locally fine, but locks beaker up when I hit publish.
A 12.8M one also fails.

**Comment by kickscondor** [comment]
Ok - wow, nearly a year later! This is working under the new Beaker. hyper://5b69209fc2dfb5eafb82e4031cd43c28ebc61e5cdd4dbdc48310bb62263f53e0/
